events { worker_connections 1024; }

http {
    server {
        listen 80;

        # 1. Frontend - Static files
        location / {
            proxy_pass http://frontend:80;
        }

        # 2. Go Transaction Service
        location /api/transfer {
            proxy_pass http://transaction:8080/transfer;
        }

        # 3. Python Balance Service
        location /api/balance/ {
            proxy_pass http://balance:8000/balance/;
        }

        # 4. Java Identity Service
        location /api/auth {
            proxy_pass http://identity:8080/auth;
        }
    }
}