events { worker_connections 1024; }

http {
    server {
        listen 80;

        # 1. Frontend - Static files
        location / {
            proxy_pass http://frontend:80;
        }

        # 2. Go Watchlist Service
        location /api/bookmark {
            proxy_pass http://transaction:8080/bookmark;
        }

        # 3. Python Screener Service
        location /api/search {
            proxy_pass http://balance:8000/search;
        }

        # 4. Java Identity Service
        location /api/auth {
            proxy_pass http://identity:8080/auth;
        }
    }
}